# Generated by Django 5.2.6 on 2025-10-29 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'estacoes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tempo_estimado_min', models.IntegerField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rotas',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='reasoninspection',
            name='description',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='RotaEstacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacao_rotas', to='railflow.estacao')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rota_estacoes', to='railflow.rota')),
            ],
            options={
                'db_table': 'rota_estacoes',
                'ordering': ['ordem'],
                'unique_together': {('rota', 'ordem')},
            },
        ),
    ]
