# Generated by Django 5.2.6 on 2025-09-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargotype',
            old_name='descrption',
            new_name='description',
        ),
    ]
