# Generated by Django 5.2.6 on 2025-09-26 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railflow', '0004_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railflow.alert')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railflow.train')),
            ],
        ),
    ]
