# Generated by Django 5.2.6 on 2025-09-30 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railflow', '0005_alertcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(verbose_name=25)),
            ],
        ),
        migrations.CreateModel(
            name='reasonMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railflow.train')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railflow.reasoninspection')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railflow.train')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railflow.reasonmaintenance')),
            ],
        ),
    ]
