# Generated by Django 5.2.6 on 2025-10-10 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railflow', '0006_reasoninspection_reasonmaintenance_inspection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railflow.cargotype')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railflow.company')),
            ],
        ),
    ]
