# Generated by Django 5.2.6 on 2025-10-10 15:09

import railflow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railflow', '0007_company_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=railflow.models.create_new_ref_number, max_length=5, unique=True),
        ),
    ]
