# Generated by Django 5.2.6 on 2025-10-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railflow', '0008_alter_company_cnpj_alter_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
