# Generated by Django 5.2.6 on 2025-10-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railflow', '0009_alter_company_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
