# Generated by Django 5.2.6 on 2025-10-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railflow', '0010_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_orders', to='railflow.station'),
        ),
        migrations.AlterField(
            model_name='order',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_orders', to='railflow.station'),
        ),
    ]
